# Generated by Django 2.1 on 2019-02-07 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('sur_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('mobil_phone', models.IntegerField()),
                ('reservation_code', models.CharField(max_length=10)),
                ('date_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PostList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('post_created', models.DateTimeField(blank=None, default=datetime.datetime.now)),
                ('text', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationDate',
            fields=[
                ('day_id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('T6_7', models.TextField(default='6:00-7:00x')),
                ('T7_8', models.TextField(default='7:00-8:00x')),
                ('T8_9', models.TextField(default='8:00-9:00x')),
                ('T9_10', models.TextField(default='9:00-10:00x')),
                ('T10_11', models.TextField(default='10:00-11:00x')),
                ('T11_12', models.TextField(default='11:00-12:00x')),
                ('T12_13', models.TextField(default='12:00-13:00x')),
                ('T13_14', models.TextField(default='13:00-14:00x')),
                ('T14_15', models.TextField(default='14:00-15:00x')),
                ('T15_16', models.TextField(default='15:00-16:00x')),
                ('T16_17', models.TextField(default='16:00-17:00x')),
                ('T17_18', models.TextField(default='17:00-18:00x')),
                ('T18_19', models.TextField(default='18:00-19:00x')),
                ('T19_20', models.TextField(default='19:00-20:00x')),
                ('T20_21', models.TextField(default='20:00-21:00x')),
                ('T21_22', models.TextField(default='21:00-22:00x')),
                ('T22_23', models.TextField(default='22:00-23:00x')),
                ('T23_24', models.TextField(default='23:00-24:00x')),
            ],
        ),
    ]
