# Generated by Django 2.1 on 2019-02-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationdate',
            name='T10_11',
            field=models.TextField(default='open'),
        ),
        migrations.AlterField(
            model_name='reservationdate',
            name='T11_12',
            field=models.TextField(default='open'),
        ),
        migrations.AlterField(
            model_name='reservationdate',
            name='T12_13',
            field=models.TextField(default='open'),
        ),
        migrations.AlterField(
            model_name='reservationdate',
            name='T13_14',
            field=models.TextField(default='open'),
        ),
        migrations.AlterField(
            model_name='reservationdate',
            name='T14_15',
            field=models.TextField(default='open'),
        ),
        migrations.AlterField(
            model_name='reservationdate',
            name='T15_16',
            field=models.TextField(default='open'),
        ),
        migrations.AlterField(
            model_name='reservationdate',
            name='T16_17',
            field=models.TextField(default='open'),
        ),
        migrations.AlterField(
            model_name='reservationdate',
            name='T17_18',
            field=models.TextField(default='open'),
        ),
        migrations.AlterField(
            model_name='reservationdate',
            name='T18_19',
            field=models.TextField(default='open'),
        ),
        migrations.AlterField(
            model_name='reservationdate',
            name='T19_20',
            field=models.TextField(default='open'),
        ),
        migrations.AlterField(
            model_name='reservationdate',
            name='T20_21',
            field=models.TextField(default='open'),
        ),
        migrations.AlterField(
            model_name='reservationdate',
            name='T21_22',
            field=models.TextField(default='open'),
        ),
        migrations.AlterField(
            model_name='reservationdate',
            name='T22_23',
            field=models.TextField(default='open'),
        ),
        migrations.AlterField(
            model_name='reservationdate',
            name='T23_24',
            field=models.TextField(default='open'),
        ),
        migrations.AlterField(
            model_name='reservationdate',
            name='T6_7',
            field=models.TextField(default='open'),
        ),
        migrations.AlterField(
            model_name='reservationdate',
            name='T7_8',
            field=models.TextField(default='open'),
        ),
        migrations.AlterField(
            model_name='reservationdate',
            name='T8_9',
            field=models.TextField(default='open'),
        ),
        migrations.AlterField(
            model_name='reservationdate',
            name='T9_10',
            field=models.TextField(default='open'),
        ),
    ]
